# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='url_shorten_form.OriginalURL')),
                ('hash', models.CharField(max_length=15)),
            ],
        ),
    ]
