# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=100)),
                ('hash', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='original',
        ),
        migrations.DeleteModel(
            name='OriginalURL',
        ),
        migrations.DeleteModel(
            name='ShortenedURL',
        ),
    ]
